### ISSUE TITLE
add support for Django

### ISSUE THREAD

**Issue by gladson** [icook/yota#29]
Would be interesting to add support for Django, if possible.

**Comment by icook** [comment]
By design yota tries to be framework agnostic, so it should already work with django, however it's possible I've missed something. I can try to throw together a simple demo if it would be helpful.

**Comment by gladson** [comment]
Very good @icook .
If you can make a demo to test.
IoI

**Comment by icook** [comment]
@gladson 
Look for one in the next couple days, I'll post it on this issue and close it when it's finished. Working on trying to push out 0.1.6 which features a much more robust JavaScript engine atm.

**Comment by gladson** [comment]
Thanks @icook , I also want to help in the project.
Bring on the next release.

**Comment by icook** [comment]
This has now been added to the yota_examples project. Took a bit longer than expected, and CSRF isn't quite there yet, but it works fine. Hope that helps.

https://github.com/icook/yota_examples

**Comment by gladson** [comment]
Here it did not work...
I did the basic install yota straight from github, but still did not work.
Still not working?

**Comment by icook** [comment]
Looks like that was my bad, that was a bug that was identified upstream and not pushed down. Should work now, just installed with a clean venv and only those packages.

**Comment by gladson** [comment]
I did so:

```
 $ git clone https://github.com/icook/yota_examples.git
 $ cd yota_examples
 $ virtualenv env_yota
 $ source env/bin/active
 (env)$ pip install git+https://github.com/icook/yota.git
 (env)$ pip install django==1.5.1
 (env)$ python manage.py runserver 0:8000
```

I did again, but nothing changed...
now this flask, very good...

once again, thank you!!!!

**Comment by icook** [comment]
Have you run syncdb? Information on what error you're getting would be very helpful, at this point I'm just guessing.

In addition, you should install the examples package. Something like:

```
pip install -e .
```

When you're in the yota_examples directory.
