### ISSUE TITLE
Fix validator tooltips overlaping

### ISSUE THREAD

**Issue by ericecook** [icook/yota#34]
This happens when two fields both have errors, and is especially noticeable with longer lists of errors. With the transparency it is pretty hard to tell what is going on and which error applies to which field

**Comment by icook** [comment]
In my mind this will be done at the same time as improving error rendering styling.

**Comment by ericecook** [comment]
Sure, but I don't see an issue open for that. Its kind of similar to #35, but not necessarily overlapping
