### ISSUE TITLE
Allow an easy way to inline validators that are essentially one off

### ISSUE THREAD

**Issue by icook** [icook/yota#48]

**Comment by ericecook** [comment]
can you explain a bit more what you are meaning? for one offs you can just define one above the form class

**Comment by icook** [comment]
For example, I've done something like this to do a one-off validator method:

```
class AddEmail(co.MappingSchema):
    """
    Allows our user to make a new comment
    """

    text = co.SchemaNode(
        co.String(), widget=fm.TextInputWidget(css_class="editInput"))

    @classmethod
    def get_add_email(cls):
        submit = de.form.Button(name="save", css_class="btnText submit add-email")
        return Form(cls(),
            buttons=(submit,),
            widget=FormWidget(
                template="empty",
                item_template='compact'),
            formtype="add_email",
        )
```

But it's messy and inconvenient. I would like a semantic that is similar to WTForms.

http://wtforms.simplecodes.com/docs/0.6/validators.html#custom-validators

**Comment by icook** [comment]
Oh, and yes you can define them before the class, but this clutters the global namespace and is an in-elegant solution. However, nothing functionally wrong with it.
