### ISSUE TITLE
override function doesn't take boolean

### ISSUE THREAD

**Issue by ericecook** [icook/yota#63]
Setting label = False used to disable label generation, now you have to set it to something like "False"

**Comment by icook** [comment]
Definitely a bug. I'll look into it.

**Comment by ericecook** [comment]
didn't fix for me

**Comment by icook** [comment]
Going to need more information than that. A test with an EntryNode works fine on my end. Are you possibly using a custom base node, or  a custom Node template that could be causing problems? Perhaps dump the values directly at the  get_context function to see what is really getting passed, as opposed to the resulting render effects.

**Comment by ericecook** [comment]
Sure. You'll notice that even though I passed a boolean False to this textarea node its passing 'False' to the context. I included another node for reference.

PYRAMID# 2013-07-19 15:17:49,370 WARNI [root][Dummy-1] {'get_list_names': <bound method TextareaNode.get_list_names of <yota.nodes.TextareaNode object at 0x7f08f413df10>>, 'errors': [], 'resolve_data': <bound method TextareaNode.resolve_data of <yota.nodes.TextareaNode object at 0x7f08f413df10>>, 'name': 'Answer', 'g': {'ajax': True, 'form_id': 'Inline_ans'}, 'title': 'Answer', 'css_class': 'textarea', 'piecewise_trigger': 'blur', 'json_identifiers': <bound method TextareaNode.json_identifiers of <yota.nodes.TextareaNode object at 0x7f08f413df10>>, 'label': 'False', 'set_identifiers': <bound method TextareaNode.set_identifiers of <yota.nodes.TextareaNode object at 0x7f08f413df10>>, 'base': 'horiz.html', 'placeholder': 'Add your answer', 'css_style': '', 'validators': [<yota.validators.RequiredValidator object at 0x3656ec0>], 'rows': '5', 'get_context': <bound method TextareaNode.get_context of <yota.nodes.TextareaNode object at 0x7f08f413df10>>, 'data': '', 'id': 'Inline_ans_Answer', 'columns': '10', 'add_error': <bound method TextareaNode.add_error of <yota.nodes.TextareaNode object at 0x7f08f413df10>>}

#PYRAMID# 2013-07-19 15:17:49,384 WARNI [root][Dummy-1] {'get_list_names': <bound method SubmitNode.get_list_names of <yota.nodes.SubmitNode object at 0x7f08f413dfd0>>, 'errors': [], 'resolve_data': <bound method SubmitNode.resolve_data of <yota.nodes.SubmitNode object at 0x7f08f413dfd0>>, 'name': 'submit', 'g': {'ajax': True, 'form_id': 'Inline_ans'}, 'title': 'Add Answer', 'css_class': '', 'piecewise_trigger': 'blur', 'json_identifiers': <bound method SubmitNode.json_identifiers of <yota.nodes.SubmitNode object at 0x7f08f413dfd0>>, 'label': True, 'set_identifiers': <bound method SubmitNode.set_identifiers of <yota.nodes.SubmitNode object at 0x7f08f413dfd0>>, 'base': 'horiz.html', 'css_style': 'float:right;', 'get_context': <bound method SubmitNode.get_context of <yota.nodes.SubmitNode object at 0x7f08f413dfd0>>, 'data': '', 'id': 'Inline_ans_submit', 'add_error': <bound method SubmitNode.add_error of <yota.nodes.SubmitNode object at 0x7f08f413dfd0>>}

**Comment by icook** [comment]
I am still not able to replicate, even with a TextArea node. Please:
1. Ensure your not running the pip version, as it does not have this patch (will be released with 0.2.2)
2. Post your Form class.
3. Post any dynamic modifications that are being made to the Form class or its attributes.

**Comment by ericecook** [comment]
Caught a stupid typo on my end, sorry
