### ISSUE TITLE
Move templates to Bootstrap 3.0

### ISSUE THREAD

**Issue by titanomachy** [icook/yota#76]
In the Jinja templates inline.html and horiz.html 'alert-error' class is used, but the default Bootstrap class of the latest version of Twitter Bootstrap is 'alert-danger' for those kind of alerts. Warnings that popup after a submit have no styling for those two templates when using alert-danger.

**Comment by icook** [comment]
I'll change this around once I get the 3.0 release out, it's taking a lot of my efforts at the moment.

**Comment by titanomachy** [comment]
If you need any help, I'll be happy to assist.
